---
- name: Automate RHEL 9 VM Provisioning
  hosts: localhost
  connection: local
  vars:

    # --- VM CONFIGURATION ---
    vm_name: "rhel-9-demo-vm"
    target_namespace: "kent-kamau-dev"
    storage_class: "gp3"
    vm_size: "u1.medium"

  tasks:
    - name: Deploy Virtual Machine instance
      kubernetes.core.k8s:
        host: "{{ api_url }}"
        api_key: "{{ api_token }}"
        validate_certs: false
        state: present
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}"
            namespace: "{{ target_namespace }}"
          spec:
            runStrategy: Always
            dataVolumeTemplates:
              - metadata:
                  name: "{{ vm_name }}-storage"
                spec:
                  sourceRef:
                    kind: DataSource
                    name: rhel9
                    namespace: openshift-virtualization-os-images
                  storage:
                    storageClassName: "{{ storage_class }}"
                    resources:
                      requests:
                        storage: 30Gi
            instancetype:
              kind: VirtualMachineClusterInstancetype
              name: "{{ vm_size }}"
            preference:
              kind: VirtualMachineClusterPreference
              name: rhel.9
            template:
              metadata:
                labels:
                  network.kubevirt.io/headlessService: headless
              spec:
                domain:
                  devices:
                    autoattachPodInterface: false
                    disks:
                      - bootOrder: 1
                        name: root-disk
                        disk:
                          bus: virtio
                      - name: cloud-init-disk # ADDED THIS
                        disk:
                          bus: virtio
                    interfaces:
                      - name: default
                        masquerade: {}
                networks:
                  - name: default
                    pod: {}
                subdomain: headless
                volumes:
                  - name: root-disk
                    dataVolume:
                      name: "{{ vm_name }}-storage"
                  - name: cloud-init-disk # MATCHED THIS
                    cloudInitNoCloud:
                      userData: |
                        #cloud-config
                        user: rhel
                        password: redhat
                        chpasswd: { expire: False }